# Generated by Django 6.0.6 on 2026-06-26 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('etablissements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='etablissements.etablissement'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.anneescolaire'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='etablissements.classe'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='eleves.eleve'),
        ),
        migrations.AddField(
            model_name='presence',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='etablissements.classe'),
        ),
        migrations.AddField(
            model_name='presence',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.eleve'),
        ),
        migrations.AddField(
            model_name='presence',
            name='enregistre_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tuteur',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.etablissement'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='tuteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='eleves.tuteur'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('eleve', 'annee')},
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('eleve', 'date', 'classe')},
        ),
    ]
