# Generated by Django 6.0.6 on 2026-06-30 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='user_compte',
            field=models.OneToOneField(blank=True, help_text="Compte de connexion de l'eleve (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_eleve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tuteur',
            name='user_compte',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion du parent (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_tuteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
