# Generated by Django 5.2.4 on 2026-07-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_eleve_user_compte_tuteur_user_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
