# Generated by Django 6.0.7 on 2026-09-25 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_alter_eleve_is_active'),
        ('etablissements', '0013_add_jour_non_ouvre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourNonOuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_jour', models.CharField(choices=[('ferie', '🎉 Jour férié'), ('conge', '🏖️ Petit congé'), ('intemperie', '⛈️ Intempéries'), ('evenement', '🎓 Événement spécial'), ('autre', '📋 Autre')], default='ferie', max_length=20)),
                ('motif', models.CharField(help_text='Ex: Tabaski, Congé de fin de trimestre...', max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etablissements.anneescolaire')),
                ('classe', models.ForeignKey(blank=True, help_text="Laisser vide pour appliquer à tout l'établissement", null=True, on_delete=django.db.models.deletion.CASCADE, to='etablissements.classe')),
                ('declare_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_non_ouvres', to='etablissements.etablissement')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('etablissement', 'date', 'classe')},
            },
        ),
    ]
