# Generated by Django 6.0.7 on 2026-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_notif",
            field=models.CharField(
                choices=[
                    ("note_modif", "Modification de note"),
                    ("note_ajout", "Ajout de note"),
                    ("paiement", "Paiement"),
                    ("absence", "Absence"),
                    ("systeme", "Systeme"),
                    ("message", "Nouveau Message"),
                ],
                max_length=20,
            ),
        ),
    ]
