# Generated by Django 6.0.6 on 2026-06-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_semaine', models.PositiveIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-libelle'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite_max', models.PositiveIntegerField(default=40)),
                ('salle', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['niveau__ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_pro', models.CharField(blank=True, max_length=30)),
                ('specialite', models.CharField(blank=True, max_length=200)),
                ('diplome', models.CharField(blank=True, max_length=200)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('conge', 'En conge'), ('inactif', 'Inactif')], default='actif', max_length=20)),
                ('salaire', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('ecole', 'Ecole Fondamentale'), ('lycee', 'Lycee'), ('universite', 'Universite'), ('centre', 'Centre de Formation'), ('institut', 'Institut')], default='ecole', max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='etablissements/logos/')),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('directeur', models.CharField(blank=True, max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('couleur_principale', models.CharField(default='#1565C0', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#0D47A1', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('bulletin', 'Bulletin de notes'), ('recu', 'Recu de paiement'), ('certificat', 'Certificat de scolarite'), ('attestation', 'Attestation de frequentation'), ('carte_scolaire', 'Carte scolaire'), ('releve_notes', 'Releve de notes')], max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('is_actif', models.BooleanField(default=True)),
                ('afficher_logo', models.BooleanField(default=True)),
                ('ligne1_gauche', models.CharField(blank=True, max_length=200)),
                ('ligne2_gauche', models.CharField(blank=True, max_length=200)),
                ('ligne3_gauche', models.CharField(blank=True, max_length=200)),
                ('ligne1_droite', models.CharField(blank=True, max_length=200)),
                ('ligne2_droite', models.CharField(blank=True, max_length=200)),
                ('ligne3_droite', models.CharField(blank=True, max_length=200)),
                ('nom_etablissement_custom', models.CharField(blank=True, max_length=200)),
                ('sous_titre_etablissement', models.CharField(blank=True, max_length=200)),
                ('afficher_adresse', models.BooleanField(default=True)),
                ('afficher_telephone', models.BooleanField(default=True)),
                ('titre_document', models.CharField(blank=True, max_length=100)),
                ('couleur_titre_bg', models.CharField(default='#555555', max_length=7)),
                ('couleur_titre_texte', models.CharField(default='#ffffff', max_length=7)),
                ('couleur_tableau_header', models.CharField(default='#dddddd', max_length=7)),
                ('couleur_tableau_texte', models.CharField(default='#000000', max_length=7)),
                ('couleur_bordure', models.CharField(default='#000000', max_length=7)),
                ('police', models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Calibri', 'Calibri'), ('Georgia', 'Georgia')], default='Arial', max_length=30)),
                ('taille_police', models.PositiveIntegerField(default=13)),
                ('col_moy_classe', models.BooleanField(default=True)),
                ('col_moy_compo', models.BooleanField(default=True)),
                ('col_moyenne_finale', models.BooleanField(default=True)),
                ('col_coefficient', models.BooleanField(default=True)),
                ('col_moy_coeffic', models.BooleanField(default=True)),
                ('col_appreciation', models.BooleanField(default=True)),
                ('note_max_classe', models.PositiveIntegerField(default=20)),
                ('note_max_compo', models.PositiveIntegerField(default=40)),
                ('afficher_moy_premier', models.BooleanField(default=True)),
                ('afficher_rang', models.BooleanField(default=True)),
                ('afficher_appre_directeur', models.BooleanField(default=True)),
                ('label_signature_gauche', models.CharField(default='Le Directeur', max_length=100)),
                ('label_signature_droite', models.CharField(default='Le Parent ou Tuteur', max_length=100)),
                ('texte_pied_page', models.TextField(blank=True)),
                ('afficher_date', models.BooleanField(default=True)),
                ('format_recu', models.CharField(choices=[('ticket', 'Ticket 80mm'), ('A5', 'A5'), ('A4', 'A4')], default='A5', max_length=10)),
                ('couleur_accent_recu', models.CharField(default='#1565C0', max_length=7)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ParametreEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('type_periode', models.CharField(choices=[('trimestre', 'Trimestres'), ('semestre', 'Semestres')], default='trimestre', max_length=20)),
                ('note_passage', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('note_max', models.DecimalField(decimal_places=2, default=20, max_digits=4)),
                ('entete_bulletin', models.TextField(blank=True)),
                ('pied_bulletin', models.TextField(blank=True)),
            ],
        ),
    ]
