# Generated by Django 6.0.6 on 2026-06-26 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationmatiere',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.matiere'),
        ),
        migrations.AddField(
            model_name='affectationmatiere',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.anneescolaire'),
        ),
        migrations.AddField(
            model_name='classe',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etablissements.anneescolaire'),
        ),
        migrations.AddField(
            model_name='classe',
            name='professeur_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affectationmatiere',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='etablissements.classe'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_enseignant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affectationmatiere',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='etablissements.enseignant'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='etablissements.etablissement'),
        ),
        migrations.AddField(
            model_name='classe',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etablissements.etablissement'),
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annees', to='etablissements.etablissement'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_documents', to='etablissements.etablissement'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='etablissements.etablissement'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='etablissements.niveau'),
        ),
        migrations.AddField(
            model_name='parametreetablissement',
            name='etablissement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='etablissements.etablissement'),
        ),
        migrations.AlterUniqueTogether(
            name='affectationmatiere',
            unique_together={('enseignant', 'classe', 'matiere', 'annee')},
        ),
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together={('etablissement', 'libelle')},
        ),
        migrations.AlterUniqueTogether(
            name='modeledocument',
            unique_together={('etablissement', 'type_document', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='niveau',
            unique_together={('etablissement', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('etablissement', 'annee', 'nom')},
        ),
    ]
