# Generated by Django 6.0.6 on 2026-07-03 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0002_initial'),
        ('notes', '0003_messagefamille'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cycle', models.CharField(choices=[('premier_cycle', '1er Cycle Fondamental (1ère–6ème)'), ('second_cycle', '2ème Cycle Fondamental (7ème–9ème)'), ('lycee', 'Lycée (10ème–12ème / Seconde–Terminale)'), ('universite', 'Université (Licence, Master, Doctorat)')], max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('mode_calcul', models.CharField(choices=[('compo', 'Moy.Classe /20 + Moy.Compo /40 → /20'), ('direct', 'Note directe /20'), ('credit', 'Crédits ECTS / UE (Université)')], default='compo', max_length=10)),
                ('note_passage', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('note_max', models.DecimalField(decimal_places=2, default=20, max_digits=4)),
                ('diplome_prepare', models.CharField(blank=True, help_text='Ex: DEF, BAC, Licence... Apparait sur les documents', max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='etablissements.etablissement')),
            ],
            options={
                'verbose_name': 'Cycle scolaire',
                'ordering': ['ordre'],
                'unique_together': {('etablissement', 'type_cycle')},
            },
        ),
        migrations.CreateModel(
            name='SerieLycee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: A, B, C, D', max_length=5)),
                ('nom', models.CharField(help_text='Ex: Sciences Exactes', max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='etablissements.cycle')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='UEUniversite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: UE101, MATH-L1', max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('credits', models.PositiveSmallIntegerField(default=3, help_text='Crédits ECTS')),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6'), (7, 'Semestre 7'), (8, 'Semestre 8')], default=1)),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('est_obligatoire', models.BooleanField(default=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='etablissements.cycle')),
            ],
            options={
                'ordering': ['semestre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MatiereCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('est_obligatoire', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres_defaut', to='etablissements.cycle')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.matiere')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('cycle', 'matiere')},
            },
        ),
        migrations.CreateModel(
            name='MatiereSerieCoef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.PositiveSmallIntegerField(default=1)),
                ('est_obligatoire', models.BooleanField(default=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.matiere')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='etablissements.serielycee')),
            ],
            options={
                'unique_together': {('serie', 'matiere')},
            },
        ),
    ]
