# Generated by Django 6.0.6 on 2026-07-03 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0003_cycle_serielycee_ueuniversite_matierecycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Serie lycee uniquement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='etablissements.serielycee'),
        ),
        migrations.AddField(
            model_name='niveau',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveaux', to='etablissements.cycle'),
        ),
    ]
