# Generated by Django 6.0.6 on 2026-07-04 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0004_classe_serie_niveau_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Fondamental, Lycée, Section Technique', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Ex: FOND, LYC, UNIV', max_length=20)),
                ('directeur_nom', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='divisions/logos/')),
                ('adresse', models.TextField(blank=True, help_text="Laisser vide pour hériter de l'établissement")),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('entete_ligne1', models.CharField(blank=True, max_length=200)),
                ('entete_ligne2', models.CharField(blank=True, max_length=200)),
                ('couleur_principale', models.CharField(default='#1565C0', max_length=7)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cycles', models.ManyToManyField(blank=True, related_name='divisions', to='etablissements.cycle')),
                ('directeur_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions_dirigees', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='etablissements.etablissement')),
            ],
            options={
                'verbose_name': 'Division',
                'ordering': ['ordre'],
                'unique_together': {('etablissement', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Division administrative (si etablissement multi-cycles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_directes', to='etablissements.division'),
        ),
        migrations.CreateModel(
            name='CycleActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.cycle')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles_actifs', to='etablissements.etablissement')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('etablissement', 'cycle')},
            },
        ),
    ]
