# Generated by Django 6.0.6 on 2026-07-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0005_division_classe_division_cycleactif'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='filiere',
            field=models.CharField(blank=True, help_text='Filière universitaire (ex: Informatique, Droit, Médecine...)', max_length=150),
        ),
        migrations.AddField(
            model_name='classe',
            name='semestre_actif',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Semestre en cours (université)', null=True),
        ),
    ]
