# Generated by Django 5.2.4 on 2026-07-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0006_classe_filiere_classe_semestre_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeledocument',
            name='contenu_personnalise',
            field=models.TextField(blank=True, help_text='Texte libre avec balises [NOM_ELEVE], [CLASSE]...'),
        ),
    ]
