# Generated by Django 5.2.4 on 2026-07-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0007_modeledocument_contenu_personnalise'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeledocument',
            name='entete_personnalise',
            field=models.TextField(blank=True, help_text='En-tête HTML pour le bulletin'),
        ),
        migrations.AddField(
            model_name='modeledocument',
            name='pied_personnalise',
            field=models.TextField(blank=True, help_text='Pied de page HTML pour le bulletin'),
        ),
    ]
