# Generated by Django 6.0.7 on 2026-07-17 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0008_modeledocument_entete_personnalise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('creer_etab', 'Création établissement'), ('modifier_etab', 'Modification établissement'), ('suspendre_etab', 'Suspension établissement'), ('reactiver_etab', 'Réactivation établissement'), ('supprimer_etab', 'Suppression établissement'), ('creer_compte', 'Création compte'), ('reset_mdp', 'Réinitialisation mot de passe'), ('bloquer_compte', 'Blocage compte'), ('debloquer_compte', 'Déblocage compte'), ('supprimer_compte', 'Suppression compte'), ('connexion', 'Connexion super admin'), ('basculer_etab', 'Basculement établissement'), ('export', 'Export rapport'), ('autre', 'Autre action')], max_length=30)),
                ('cible', models.CharField(blank=True, help_text='Description de la cible (nom étab, username...)', max_length=200)),
                ('detail', models.TextField(blank=True, help_text="Détail de l'action")),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journal', to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_actions', to='etablissements.etablissement')),
            ],
            options={
                'verbose_name': 'Journal action',
                'verbose_name_plural': 'Journal des actions',
                'ordering': ['-date'],
            },
        ),
    ]
