# Generated by Django 6.0.7 on 2026-07-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0009_journal_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plateforme', models.CharField(default='SmartSchool ERP', max_length=100)),
                ('slogan', models.CharField(blank=True, default='Gérez votre école en toute simplicité.', max_length=200)),
                ('email_support', models.EmailField(blank=True, default='support@smartschool.ml', max_length=254)),
                ('telephone_support', models.CharField(blank=True, max_length=20)),
                ('site_web', models.URLField(blank=True)),
                ('logo_plateforme', models.ImageField(blank=True, null=True, upload_to='plateforme/')),
                ('couleur_primaire', models.CharField(default='#1565C0', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#0D47A1', max_length=7)),
                ('mentions_legales', models.TextField(blank=True)),
                ('message_accueil', models.TextField(blank=True, help_text='Message affiché sur la page de connexion')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres réseau',
            },
        ),
    ]
