# Generated by Django 6.1 on 2026-08-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0010_parametres_reseau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='nb_compositions_trimestre',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre de compositions par trimestre pour ce cycle. 1 = saisie directe de moy_compo (comportement standard). 2+ = l'enseignant saisit chaque composition séparément, moy_compo est alors calculé automatiquement."),
        ),
    ]
