# Generated by Django 6.0.7 on 2026-09-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0011_compositions_multiples'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresreseau',
            name='conditions_utilisation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parametresreseau',
            name='domaine_personnalise',
            field=models.CharField(blank=True, help_text='Ex: portail.ecole-babemba.ml', max_length=150),
        ),
    ]
