# Generated by Django 6.0.7 on 2026-09-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0012_parametresreseau_conditions_utilisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametresreseau',
            name='conditions_utilisation',
        ),
        migrations.RemoveField(
            model_name='parametresreseau',
            name='domaine_personnalise',
        ),
    ]
