# Generated by Django 6.0.6 on 2026-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin', 'Administrateur'), ('comptable', 'Comptable'), ('enseignant', 'Enseignant'), ('surveillant', 'Surveillant General'), ('parent', 'Parent'), ('eleve', 'Eleve'), ('personnel', 'Personnel')], default='personnel', max_length=20),
        ),
    ]
