# Generated by Django 6.0.6 on 2026-07-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('etablissements', '0005_division_classe_division_cycleactif'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Division géree (si établissement multi-cycles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='etablissements.division'),
        ),
    ]
