# Generated by Django 6.0.7 on 2026-07-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('etablissements', '0010_parametres_reseau'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec'), ('bloque', 'Compte bloqué')], default='succes', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etablissements.etablissement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal connexion',
                'ordering': ['-date'],
            },
        ),
    ]
