# Generated by Django 6.0.7 on 2026-09-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_journal_connexion'),
        ('etablissements', '0011_compositions_multiples'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.AddField(
            model_name='user',
            name='divisions',
            field=models.ManyToManyField(blank=True, help_text='Divisions gérées par cet utilisateur. Vide = accès à tous les cycles (super admin / admin global).', related_name='utilisateurs', to='etablissements.division'),
        ),
    ]
