# Generated by Django 6.0.6 on 2026-06-26 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('etablissements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_conduite', models.BooleanField(default=False, help_text='Matiere de conduite/comportement')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.etablissement')),
            ],
            options={
                'ordering': ['nom'],
                'unique_together': {('etablissement', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.CharField(max_length=5)),
                ('heure_fin', models.CharField(max_length=5)),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois', to='etablissements.classe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.etablissement')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='NotePeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moy_classe', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moy_compo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_max_classe', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('note_max_compo', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('note_conduite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('valeur_avant_modif', models.CharField(blank=True, help_text='Sauvegarde avant modification', max_length=100)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_periode', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.matiere')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_modifiees', to=settings.AUTH_USER_MODEL)),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note de periode',
            },
        ),
        migrations.CreateModel(
            name='LogModificationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_modifiant', models.CharField(max_length=20)),
                ('champ_modifie', models.CharField(max_length=30)),
                ('valeur_avant', models.CharField(blank=True, max_length=50)),
                ('valeur_apres', models.CharField(blank=True, max_length=50)),
                ('date_modif', models.DateTimeField(auto_now_add=True)),
                ('notif_envoyee', models.BooleanField(default=False)),
                ('notif_lue', models.BooleanField(default=False)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note_periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notes.noteperiode')),
            ],
            options={
                'verbose_name': 'Log modification note',
                'ordering': ['-date_modif'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('trimestre', 'Trimestre'), ('semestre', 'Semestre')], default='trimestre', max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('libelle', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.anneescolaire')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.etablissement')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('etablissement', 'annee', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='noteperiode',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.periode'),
        ),
        migrations.AlterUniqueTogether(
            name='noteperiode',
            unique_together={('eleve', 'matiere', 'classe', 'periode')},
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang', models.PositiveIntegerField(blank=True, null=True)),
                ('effectif_classe', models.PositiveIntegerField(blank=True, null=True)),
                ('appreciation', models.TextField(blank=True)),
                ('is_valide', models.BooleanField(default=False)),
                ('date_generation', models.DateTimeField(auto_now=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.eleve')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.periode')),
            ],
            options={
                'unique_together': {('eleve', 'periode')},
            },
        ),
    ]
