# Generated by Django 6.0.6 on 2026-06-30 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_eleve_user_compte_tuteur_user_compte'),
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_auteur', models.CharField(blank=True, max_length=20)),
                ('motif', models.TextField(help_text='Explication de la reclamation')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('acceptee', 'Acceptee'), ('rejetee', 'Rejetee')], default='en_attente', max_length=20)),
                ('reponse', models.TextField(blank=True, help_text="Reponse de l'administration")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_envoyees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='eleves.eleve')),
                ('note_periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='notes.noteperiode')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclamation',
                'ordering': ['-date_creation'],
            },
        ),
    ]
