# Generated by Django 6.0.6 on 2026-07-02 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_eleve_user_compte_tuteur_user_compte'),
        ('etablissements', '0002_initial'),
        ('notes', '0002_reclamation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFamille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire_role', models.CharField(choices=[('directeur', 'Directeur'), ('comptable', 'Comptable'), ('surveillant', 'Surveillant General'), ('enseignant', 'Enseignant (matiere concernee)'), ('administration', 'Administration (tous)')], max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('corps', models.TextField()),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('repondu', 'Repondu')], default='non_lu', max_length=10)),
                ('reponse', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('destinataire_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='eleves.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.etablissement')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('repondu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_repondus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message famille',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
