# Generated by Django 6.0.6 on 2026-07-05 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_eleve_user_compte_tuteur_user_compte'),
        ('etablissements', '0006_classe_filiere_classe_semestre_actif'),
        ('notes', '0003_messagefamille'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, help_text='Note /20', max_digits=4, null=True)),
                ('note_rattrapage', models.DecimalField(blank=True, decimal_places=2, help_text='Note de rattrapage /20', max_digits=4, null=True)),
                ('credits_valides', models.BooleanField(default=False, help_text='Crédits validés (note >= 10)')),
                ('mention', models.CharField(blank=True, max_length=20)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_ue', to='eleves.eleve')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.periode')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_ue_saisies', to=settings.AUTH_USER_MODEL)),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etablissements.ueuniversite')),
            ],
            options={
                'ordering': ['ue__semestre', 'ue__code'],
                'unique_together': {('eleve', 'ue', 'classe', 'periode')},
            },
        ),
    ]
