# Generated by Django 5.2.4 on 2026-07-11 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_noteue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='cloture_par',
            field=models.ForeignKey(blank=True, help_text='Administrateur ayant clôturé la saisie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_cloturees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periode',
            name='date_cloture',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle la saisie a été clôturée.', null=True),
        ),
        migrations.AddField(
            model_name='periode',
            name='saisie_cloturee',
            field=models.BooleanField(default=False, help_text='Si vrai, toute saisie/modification de notes est bloquée sur cette période.'),
        ),
    ]
