# Generated by Django 6.0.7 on 2026-07-23 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_periode_cloture_par_periode_date_cloture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteperiode',
            name='note_conduite',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Note de conduite sur 18', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)]),
        ),
    ]
