# Generated by Django 6.1 on 2026-08-08 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_alter_eleve_is_active'),
        ('etablissements', '0011_compositions_multiples'),
        ('notes', '0006_conduite_max_18'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='1ère, 2ème, 3ème composition...')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note_max', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.matiere')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.periode')),
                ('saisi_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compositions_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Composition',
                'verbose_name_plural': 'Compositions',
                'ordering': ['numero'],
                'unique_together': {('eleve', 'matiere', 'classe', 'periode', 'numero')},
            },
        ),
    ]
