# Generated by Django 6.0.7 on 2026-09-02 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_alter_eleve_is_active'),
        ('etablissements', '0011_compositions_multiples'),
        ('notes', '0007_compositions_multiples'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='composition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='composition',
            name='annee',
            field=models.ForeignKey(blank=True, help_text='Année scolaire structurante (1er cycle)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='etablissements.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='note_max',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='composition',
            name='periode',
            field=models.ForeignKey(blank=True, help_text='Période optionnelle (compatibilité future)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.periode'),
        ),
        migrations.AlterUniqueTogether(
            name='composition',
            unique_together={('eleve', 'matiere', 'classe', 'annee', 'numero')},
        ),
    ]
