# Generated by Django 6.0.6 on 2026-06-26 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
        ('etablissements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant_defaut', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('is_obligatoire', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Especes'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement')], default='especes', max_length=20)),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('annule', 'Annule'), ('attente', 'En attente')], default='valide', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eleves.eleve')),
                ('encaisse_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.etablissement')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.typefrais')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
