# Generated by Django 5.2.4 on 2026-07-11 14:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0003_eleve_user_compte_tuteur_user_compte'),
        ('etablissements', '0006_classe_filiere_classe_semestre_actif'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefrais',
            name='annee',
            field=models.ForeignKey(blank=True, help_text="Année scolaire concernée. Si vide, s'applique à toutes les années (legacy).", null=True, on_delete=django.db.models.deletion.CASCADE, to='etablissements.anneescolaire'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1, message='Le montant doit être strictement positif.')]),
        ),
        migrations.CreateModel(
            name='ReductionFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, default=0, help_text='Montant fixe réduit.', max_digits=12)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('date_accord', models.DateTimeField(default=django.utils.timezone.now)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='eleves.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.etablissement')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.typefrais')),
            ],
            options={
                'unique_together': {('eleve', 'annee', 'type_frais')},
            },
        ),
    ]
