# Generated by Django 5.2.4 on 2026-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_paiement_annule_par_paiement_date_annulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='periode_payee',
            field=models.CharField(blank=True, help_text='Mois ou Tranche réglée (ex: Novembre, Tranche 1)', max_length=50),
        ),
        migrations.AddField(
            model_name='typefrais',
            name='nombre_tranches',
            field=models.IntegerField(blank=True, default=1, help_text='Si périodicité par tranches, combien de tranches ?'),
        ),
        migrations.AddField(
            model_name='typefrais',
            name='periodicite',
            field=models.CharField(choices=[('unique', 'Paiement Unique'), ('mensuel', 'Mensuel'), ('tranches', 'Par Tranches')], default='unique', max_length=20),
        ),
    ]
