# Generated by Django 6.0.7 on 2026-07-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0004_alter_eleve_is_active'),
        ('etablissements', '0010_parametres_reseau'),
        ('finances', '0004_paiement_periode_payee_typefrais_nombre_tranches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Numéro de la tranche (1, 2, 3...)')),
                ('libelle', models.CharField(help_text='Ex: Tranche 1', max_length=50)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a_payer', 'À payer'), ('payee', 'Payée'), ('retard', 'En retard'), ('dispensee', 'Dispensée')], db_index=True, default='a_payer', max_length=12)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='eleves.eleve')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissements.etablissement')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeances_liees', to='finances.paiement')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='finances.typefrais')),
            ],
            options={
                'ordering': ['eleve', 'numero'],
                'unique_together': {('eleve', 'annee', 'type_frais', 'numero')},
            },
        ),
    ]
